name: linter-check

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          chmod +x brain_games/scripts/brain_games.py
          make lint